### ISSUE TITLE
Messenger bugs

### ISSUE THREAD

**Issue by Bunnbuns** [versocre/svaurora#4]
The buttons on svaurora.gq/messenger.html (new message and refresh) when using the light theme and hovering over them makes the text inside disappear (the same color as the background of the button)
Also, the themes, in general, seem to take a split second to update (the page is dark theme until the page is done loading and goes back to the light theme I chose)

❤

**Comment by versocre** [comment]
I've noticed the button issue for awhile on Messenger and it just requires a small css change but I keep forgetting. Thanks for the report! The text on buttons disappearing depends on what browser you are using. For example, on Safari for iOS, the text is "hidden" on all buttons. The themes of Aurora are made with variables and certain browsers don't support them that well. 

Google Chrome is the browser I use to develop and design Aurora and there aren't usually much issues with it on there compared to other browsers. The Messenfer button issue is on Chrome too however. 

I'll try my best to fix all of the buttons that have this issue but again, it just depends on what browser you're using typically. 

This issue will now be closed and will be fixed in a few days. Thanks!
